splits:
  Bilibili:
    list: bilibili
    priority: global
    exclude_tags: [ads]
    cn:
      exclude_tags: ["!cn"]
    global:
      require_tags: ["!cn"]

  Game:
    list: category-games-cn
    global_list: category-games-!cn
    cn_extra_list: category-games-!cn
    cn_extra_require_tags: [cn]
    priority: cn
    exclude_tags: [ads]
    cn:
      exclude_tags: ["!cn"]
    global:
      exclude_tags: [cn]

  Apple:
    list: apple
    priority: cn
    exclude_tags: [ads]
    cn:
      require_tags: [cn]
    global:
      exclude_tags: [cn]

  Microsoft:
    list: microsoft
    priority: cn
    exclude_tags: [ads]
    cn:
      require_tags: [cn]
    global:
      exclude_tags: [cn]

  Google:
    list: google
    priority: cn
    exclude_tags: [ads]
    cn:
      require_tags: [cn]
    global:
      exclude_tags: [cn]

groups:
  AI:
    lists: [category-ai-!cn]
    exclude_tags: [cn, ads]

  Streaming:
    lists: [youtube, netflix, disney, hbo, spotify, bahamut, tiktok, primevideo]
    exclude_tags: [cn, ads]

  Telegram:
    lists: [telegram]
    exclude_tags: [cn, ads]

  Social:
    lists: [facebook, instagram, twitter]
    exclude_tags: [cn, ads]

china_domain_list: geolocation-cn
china_domain_extra_outputs:
  - Bilibili_CN
  - Game_CN
  - Apple_CN
  - Microsoft_CN
  - Google_CN

no_resolve_outputs:
  - Telegram
